name: README Basic Check

on:
  push:
    paths:
      - "README.md"
  pull_request:
    paths:
      - "README.md"

jobs:
  check-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Simple Markdown Check
        run: |
          echo "Checking README exists..."
          test -f README.md

          echo "Checking file is not empty..."
          test -s README.md

          echo "Basic check passed ✅"
